import type { Metadata } from "next";
import { Noto_Sans_Thai, Noto_Sans_Thai_Looped } from "next/font/google";
import "./globals.css";


import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/Sidebar"



const noto = Noto_Sans_Thai({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['thai'],
});

const noto2 = Noto_Sans_Thai_Looped({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['thai'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={` `}
        suppressHydrationWarning
      >
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <SidebarProvider>
              <div className="w-full flex flex-col h-screen overflow-hidden">
                <Navbar />
                <div className="flex flex-1 min-h-0">
                  <AppSidebar />
                  <main className="flex-1 overflow-y-auto">
                    {children}
                  </main>
                </div>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
